<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PersonaService" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/MiServicioWcf.Modelo" />
      <xs:import namespace="http://schemas.datacontract.org/2004/07/MiServicioWcf" />
      <xs:element name="Consultar">
        <xs:complexType>
          <xs:sequence />
        </xs:complexType>
      </xs:element>
      <xs:element name="ConsultarResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/MiServicioWcf.Modelo" minOccurs="0" name="ConsultarResult" nillable="true" type="q1:ArrayOfTBDATA_PERSONAS" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ListarClientes">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="psCodEmpresa" nillable="true" type="xs:string" />
            <xs:element minOccurs="0" name="conexion" nillable="true" type="xs:string" />
            <xs:element minOccurs="0" name="pdCodAplicativo" type="xs:double" />
            <xs:element minOccurs="0" name="pdCodProducto" type="xs:double" />
            <xs:element minOccurs="0" name="pdCodSubProd" type="xs:double" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ListarClientesResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q2="http://schemas.datacontract.org/2004/07/MiServicioWcf" minOccurs="0" name="ListarClientesResult" nillable="true" type="q2:ArrayOfPersonaCliente" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="anyType" nillable="true" type="xs:anyType" />
      <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
      <xs:element name="boolean" nillable="true" type="xs:boolean" />
      <xs:element name="byte" nillable="true" type="xs:byte" />
      <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
      <xs:element name="decimal" nillable="true" type="xs:decimal" />
      <xs:element name="double" nillable="true" type="xs:double" />
      <xs:element name="float" nillable="true" type="xs:float" />
      <xs:element name="int" nillable="true" type="xs:int" />
      <xs:element name="long" nillable="true" type="xs:long" />
      <xs:element name="QName" nillable="true" type="xs:QName" />
      <xs:element name="short" nillable="true" type="xs:short" />
      <xs:element name="string" nillable="true" type="xs:string" />
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
      <xs:element name="char" nillable="true" type="tns:char" />
      <xs:simpleType name="char">
        <xs:restriction base="xs:int" />
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration" />
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid" />
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName" />
      <xs:attribute name="Id" type="xs:ID" />
      <xs:attribute name="Ref" type="xs:IDREF" />
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/MiServicioWcf.Modelo" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/MiServicioWcf.Modelo" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:complexType name="ArrayOfTBDATA_PERSONAS">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="TBDATA_PERSONAS" nillable="true" type="tns:TBDATA_PERSONAS" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfTBDATA_PERSONAS" nillable="true" type="tns:ArrayOfTBDATA_PERSONAS" />
      <xs:complexType name="TBDATA_PERSONAS">
        <xs:sequence>
          <xs:element minOccurs="0" name="EMPRESA_CODIGO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_ANEXO_OF" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_APEMAT" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_APEPAT" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_CATEGORIA" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_CEPRO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_CERT_INSCR" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_CODIGO" type="xs:double" />
          <xs:element minOccurs="0" name="PERSONA_COD_SISTEMA" nillable="true" type="xs:double" />
          <xs:element minOccurs="0" name="PERSONA_CUII" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_DIAS_CREDITO" nillable="true" type="xs:double" />
          <xs:element minOccurs="0" name="PERSONA_DIRECCION" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_DIST" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_DPTO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_EMAIL" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_EMAIL2" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_ESTADO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_ESTADO_SUNAT" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_EXTRANJERO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_FAX1" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_FAX2" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_FECHANAC" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_FORMA_PAGO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_NOMBRES" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_NOMBRE_COMERCIAL" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_NOMBRE_CONTACTO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_PADRON" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_PAIS" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_PERSON_CODIGO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_PROV" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_PROVEE" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_PROVIENE" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_PROVIENE_CODIGO" nillable="true" type="xs:double" />
          <xs:element minOccurs="0" name="PERSONA_RAZON_SOCIAL" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_REFERENCIA" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_RESPONSABLE_SOLUCION" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_RUBRO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_RUC" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_SYS_CRE" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_SYS_EST" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_SYS_MOD" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_TELF1" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_TELF2" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_TELF_CELULAR" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_TELF_OF" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_TIPO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_TIPO_CLIENTE" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_URBANIZACION" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_USER" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_WEB" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PERSONA_WEB2" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="TBDATA_PERSONAS" nillable="true" type="tns:TBDATA_PERSONAS" />
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/MiServicioWcf" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/MiServicioWcf" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:complexType name="ArrayOfPersonaCliente">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="PersonaCliente" nillable="true" type="tns:PersonaCliente" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfPersonaCliente" nillable="true" type="tns:ArrayOfPersonaCliente" />
      <xs:complexType name="PersonaCliente">
        <xs:sequence>
          <xs:element minOccurs="0" name="CARCON_APLICATIVO" type="xs:double" />
          <xs:element minOccurs="0" name="CARCON_CODIGO" type="xs:double" />
          <xs:element minOccurs="0" name="CARCON_CONSULTA" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="CARCON_PRODUCTO" type="xs:double" />
          <xs:element minOccurs="0" name="CARCON_SOLUCION" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="CARCON_SUBPRODUCTO" type="xs:double" />
          <xs:element minOccurs="0" name="CARCON_TRANSACCION" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ListaClienteDt" nillable="true" type="tns:ArrayOfPersonaCliente" />
          <xs:element minOccurs="0" name="NIVEL1_DESCRIP" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="PRODUCTO" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="SUBPRODUCTO" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="PersonaCliente" nillable="true" type="tns:PersonaCliente" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IPersona_Consultar_InputMessage">
    <wsdl:part name="parameters" element="tns:Consultar" />
  </wsdl:message>
  <wsdl:message name="IPersona_Consultar_OutputMessage">
    <wsdl:part name="parameters" element="tns:ConsultarResponse" />
  </wsdl:message>
  <wsdl:message name="IPersona_ListarClientes_InputMessage">
    <wsdl:part name="parameters" element="tns:ListarClientes" />
  </wsdl:message>
  <wsdl:message name="IPersona_ListarClientes_OutputMessage">
    <wsdl:part name="parameters" element="tns:ListarClientesResponse" />
  </wsdl:message>
  <wsdl:portType name="IPersona">
    <wsdl:operation name="Consultar">
      <wsdl:input wsaw:Action="http://tempuri.org/IPersona/Consultar" message="tns:IPersona_Consultar_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IPersona/ConsultarResponse" message="tns:IPersona_Consultar_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="ListarClientes">
      <wsdl:input wsaw:Action="http://tempuri.org/IPersona/ListarClientes" message="tns:IPersona_ListarClientes_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IPersona/ListarClientesResponse" message="tns:IPersona_ListarClientes_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IPersona" type="tns:IPersona">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Consultar">
      <soap:operation soapAction="http://tempuri.org/IPersona/Consultar" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ListarClientes">
      <soap:operation soapAction="http://tempuri.org/IPersona/ListarClientes" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PersonaService">
    <wsdl:port name="BasicHttpBinding_IPersona" binding="tns:BasicHttpBinding_IPersona">
      <soap:address location="http://localhost:63532/PersonaService.svc" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>